### PR TITLE
Add env var for loc.db path

### PR DESCRIPTION
**Pull request by jamesnunn**
Adds customisable location for the loc.db download
to allow apps to function if the module is not
writeable by the user e.g. with AWS lambdas.

The entire path and filename is required:

`GEOGRAPY_DB=/path/to/loc.db`

### CODE REVIEW

**Comment by jamesnunn** [comment]
Wrong target

**Comment by WolfgangFahl** [comment]
Thx for the comment- Why did you close this and how did you work around the problem?

**Comment by jamesnunn** [comment]
Hi sorry, I'd forked and updated it for our own use it because I wasn't sure the change would be accepted as soon as we need to use it. I can redo it though since you're responding quickly. I just set the loc.db path as an environment variable. I need to add a test too.

**Comment by WolfgangFahl** [comment]
thx for the swift answer - this would be great

**Comment by WolfgangFahl** [comment]
We'd love to hear about your usecase. Feel free to join our chat!

**Pull request closed without merging**
